setup:
  - sudo apt-get -qqq -o Acquire::Check-Valid-Until=false -o Acquire::Check-Date=false update
  - sudo apt-get -qqq update -y
  - sudo apt-get -qqq install -y git wget dos2unix
  - sudo DEBIAN_FRONTEND=noninteractive apt-get -qqq install -y debconf-utils
  - sudo debconf-set-selections <<< "'"debconf debconf/frontend select Noninteractive"'"
  - sudo debconf-set-selections <<< "'"mysql-server mysql-server/root_password password {{mysql_pass}}"'"
  - sudo debconf-set-selections <<< "'"mysql-server mysql-server/root_password_again password {{mysql_pass}}"'"

jobs:
  - name: itrust-build
    steps: 
      - name: install JRE
        run: sudo apt-get install default-jre -y
      - name: install JDK
        run: sudo apt-get -qqq install openjdk-11-jdk -y
      - name: install Maven
        run: sudo apt-get -qqq install maven -y ; export PATH=/opt/apache-maven-3.8.4/bin:$PATH 
      - name: install nodejs
        run: sudo apt-get -qqq install nodejs -y
      - name: install npm
        run: sudo apt-get -qqq install npm -y   
      - name: install mysql
        run: sudo apt-get -qqq install -y mysql-server
      - name: Delete old itrust
        run: sudo rm -rf iTrust2-v10
      - name: clone iTrust
        run: git clone --recursive https://{{git_token}}@github.ncsu.edu/engr-csc326-staff/iTrust2-v10.git
      - name: create application.yml file
        run: cp iTrust2-v10/iTrust2/src/main/resources/application.yml.template iTrust2-v10/iTrust2/src/main/resources/application.yml
      - name: set password in application.yml
        run: sed -i "'"s/password\:/password\:\ {{mysql_pass}}/g"'" iTrust2-v10/iTrust2/src/main/resources/application.yml
      - name: copy patch
        run: sudo cp -rp {{shared_path}}/patch/Itrust.patch ~/iTrust2-v10
      - name: fix patch
        run: cd ~/iTrust2-v10 && git apply Itrust.patch
      - name: test iTrust1
        run: mvn -f iTrust2-v10/iTrust2 --batch-mode --update-snapshots clean test
      - name: create war file
        run: mvn -f iTrust2-v10/iTrust2 clean package
  
  - name: mutation-coverage
    mutation:
      url: https://github.com/chrisparnin/checkbox.io-micro-preview
      iterations: 1000
      snapshots:
       - http://localhost:3000/survey/long.md
       - http://localhost:3000/survey/upload.md
       - http://localhost:3000/survey/survey.md
       - http://localhost:3000/survey/variations.md

  - name: itrust-deploy
    homePage: iTrust2-10/login
    sourceFileLoc: iTrust2-v10/iTrust2/target/iTrust2-10.war
    deployFileLoc: /opt/tomcat/webapps/
    server: tomcat
    port: 8080
    steps: 
      - name: install JRE
        run: sudo apt-get install default-jre -y
      - name: install JDK
        run: sudo apt-get -qqq install openjdk-11-jdk -y
      - name: install Maven
        run: sudo apt-get -qqq install maven -y ; export PATH=/opt/apache-maven-3.8.4/bin:$PATH 
      - name: install nodejs
        run: sudo apt-get -qqq install nodejs -y
      - name: install npm
        run: sudo apt-get -qqq install npm -y   
      - name: install mysql
        run: sudo apt-get -qqq install -y mysql-server